name: app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  get: ^4.6.6
  iconsax: ^0.0.8
  iconly: ^1.0.1
  hugeicons: ^0.0.7
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
          weight: 500
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 900
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 700
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
